# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [58]:
import sys
import numpy as np


## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [59]:
python_arr = [0] * 1000
print(sys.getsizeof(python_arr))


8056


In [60]:
np_arr = np.zeros(1000, dtype=np.int8)
print(np_arr.nbytes)


1000


## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [61]:
length = np.random.randint(5, 11)

arr = np.random.uniform(0, 10.0, length)

elems = arr[[0, 2, -1]]
print(elems)


[4.6968309  2.94819249 3.27342902]


## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [62]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])

result = array[[0, 1, 4, -1]].sum()
print(result == 27.0)


True


## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [63]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [64]:
A.mean(axis=0)


array([2. , 8.4])

### Task 5.2 Get the standard deviation by `y` axis

In [65]:
A.std(axis=1)


array([2.5, 3. , 4. , 3.5, 3. ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [66]:
A.sum(axis=1)


array([ 7, 10, 14, 13,  8])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [67]:
A[:2]


array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [68]:
A[::2]


array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [ ]:
# Python code
%timeit [i for i in range(1000000)]


In [ ]:
%timeit np.arange(1000000)


### Task 6.2

In [ ]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%timeit unknown_signature(vector1, vector2)


In [ ]:
%timeit np.dot(vector1, vector2)


### Task 6.3

In [ ]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

%timeit unknown_signature(matrix1, matrix2)


In [ ]:
mtx1 = np.array(matrix1)
mtx2 = np.array(matrix2)

%timeit mtx1 * mtx2


### Task 6.4

In [ ]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]

%timeit unknown_signature(lst)


In [ ]:
%timeit np.array(lst).mean()


## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [ ]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst


In [ ]:
np_lst = np.array(lst)
np_lst[mask] = new_value
np_lst


### Task 7.2

In [ ]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or


In [ ]:
np_ls1 = np.array(list1)
np_ls2 = np.array(list2)

np_bitwise_complement = np.invert(np_ls1)
np_bitwise_and = np.bitwise_and(np_ls1, np_ls2)
np_bitwise_or = np.bitwise_or(np_ls1, np_ls2)

np_bitwise_complement, np_bitwise_and, np_bitwise_or


### Task 7.3 Optional

In [ ]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style


In [ ]:
np_list = np.array(my_list)

mask = (np_list % 2 == 0) & ((np_list % 3 == 0) | (np_list > 10))

result = (np.bitwise_xor(np_list[mask], 7)) + 2
result
