# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [63]:
import sys
import numpy as np
import datetime


## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [64]:
# write your code here (for Python default syntax)
arr = [0] * 1000
sys.getsizeof(arr)

8056

In [65]:
# write your code here (for numpy syntax)
sys.getsizeof(np.array(arr, dtype=np.int8))

1112

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [66]:
# write your code here

arr = np.array([1.1, 2.3, 3.3, 6.2, 3.5])
arr[[0, 2, -1]]


array([1.1, 3.3, 3.5])

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [67]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
# write your code here
array[[0, 1, 4, -1]].sum()

27.0

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [68]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [69]:
# write your code here
A.mean(axis=1)

array([3.5, 5. , 7. , 6.5, 4. ])

### Task 5.2 Get the standard deviation by `y` axis

In [70]:
# write your code here
A.std()

3.515679166249389

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [71]:
# write your code here
A.sum()

52

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [72]:
# write your code here
A[:2]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [73]:
# write your code here
A[::2]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [76]:
# Python code
start_time_1 = datetime.datetime.now()
result_python = [i for i in range(1000000)]
end_time_1 = datetime.datetime.now()
print((end_time_1 - start_time_1).total_seconds())

0.077999


In [79]:
# write your numpy code here and estimate the time of execution
start_time_2 = datetime.datetime.now()
result_numpy = np.arange(1000000)
end_time_2 = datetime.datetime.now()
print((end_time_2 - start_time_2).total_seconds())

0.002003


### Task 6.2

In [80]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%time unknown_signature(vector1, vector2)
result  

CPU times: total: 0 ns
Wall time: 0 ns


0

In [83]:
# write your numpy code here and estimate the time of execution
def code_with_numpy(vector1, vector2):
  result = np.dot(vector1, vector2)
  return result

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

%time code_with_numpy(vector1, vector2)


CPU times: total: 0 ns
Wall time: 0 ns


32

### Task 6.3

In [92]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

print(unknown_signature(matrix1, matrix2))

[[5, 12], [21, 32]]


In [91]:
# write your numpy code here and estimate the time of execution

def code_with_numpy(matrix1, matrix2):
  result = np.multiply(matrix1, matrix2)
  return result.tolist()


matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

print(code_with_numpy(matrix1, matrix2))

[[5, 12], [21, 32]]


### Task 6.4

In [90]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]
print(unknown_signature(lst))

3.0


In [89]:
# write your numpy code here and estimate the time of execution
def code_with_numpy(lst):
  result = np.mean(lst)
  return result
  

lst = [1, 2, 3, 4, 5]
print(code_with_numpy(lst))

3.0


## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [ ]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[0, 2, 0, 4, 0]

In [96]:
# write your numpy code here
def code_with_numpy(lst, mask, new_value):
    lst = np.array(lst)
    lst[mask] = new_value
    return lst.tolist()
lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0

code_with_numpy(lst, mask, new_value)
    

[0, 2, 0, 4, 0]

### Task 7.2

In [ ]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [98]:
# write your numpy code here

def code_with_numpy(lst1, lst2):
  bitwise_complement = np.bitwise_not(lst1)
  bitwise_and = np.bitwise_and(lst1, lst2)
  bitwise_or = np.bitwise_or(lst1, lst2)
  return bitwise_complement.tolist(), bitwise_and.tolist(), bitwise_or.tolist()

list1 = np.array([5, 2, 7, 4, 9])
list2 = np.array([3, 6, 1, 8, 10])

result_bitwise_complement, result_bitwise_and, result_bitwise_or = code_with_numpy(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

### Task 7.3 Optional

In [ ]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [99]:
# write your numpy code here

def code_with_numpy(lst):
  arr = np.array(lst)
  mask = (arr % 2 == 0) & ((arr % 3 ==0 ) | (arr > 10))
  modified_num = (arr[mask] ^ 7) + 2
  
  return modified_num.tolist()
my_list = [6, 9, 12, 14, 17, 20]
result_python_style = code_with_numpy(my_list)
result_python_style

[3, 13, 11, 21]