# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [1]:
import sys
import numpy as np
import random
import time

In [18]:
def timeit(func):
    def timed(*args, **kwargs):
        start = time.perf_counter_ns()
        result = func(*args, **kwargs)
        end = time.perf_counter_ns()
        print((end - start), "nano-secs")
        return result
    return timed

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [9]:
python_array = [random.choice(range(10)) for i in range(1000)]
sys.getsizeof(python_array)

8856

In [15]:
numpy_array = np.random.choice(np.arange(10, dtype=np.int8), size=1000)
sys.getsizeof(numpy_array)

[2 1 3 0 8 0 9 3 0 3 6 4 9 2 1 8 4 8 4 4 6 2 6 1 9 5 9 2 7 0 9 2 9 4 4 5 0
 3 5 8 6 2 7 8 6 8 0 8 8 8 3 4 4 8 9 7 9 7 6 8 7 8 9 3 5 4 2 2 8 3 3 7 8 6
 8 8 4 3 5 6 7 9 7 5 8 5 3 3 0 6 4 5 1 3 9 5 1 2 5 0 9 7 3 2 2 5 1 4 9 2 9
 4 0 8 7 8 5 3 2 5 7 0 8 4 9 2 2 9 5 0 8 7 4 1 3 8 7 2 5 1 5 2 0 4 5 6 7 5
 5 5 7 4 6 8 4 5 2 8 1 2 8 1 0 9 7 7 1 1 8 8 5 7 8 4 4 6 2 7 7 7 0 1 1 6 3
 9 8 5 0 9 5 7 2 5 8 8 4 7 4 9 3 3 3 7 6 8 1 4 2 8 3 6 5 1 5 2 7 5 5 0 3 8
 1 1 2 5 7 7 3 2 9 3 4 8 9 6 5 8 8 5 3 1 1 5 3 9 7 5 5 8 2 2 1 5 5 7 4 8 3
 0 4 5 6 7 0 8 1 5 3 2 1 5 9 0 7 9 9 4 5 7 7 9 7 1 4 4 4 4 6 6 0 5 7 7 2 0
 0 8 7 2 7 3 5 4 8 4 6 8 5 5 2 9 6 3 4 5 5 1 3 4 1 8 0 2 0 0 5 2 2 0 9 1 8
 8 1 6 9 0 2 0 4 3 4 7 8 5 2 0 0 1 7 8 9 0 0 8 6 3 2 1 7 7 1 3 4 4 7 2 7 7
 5 9 7 1 2 4 0 7 6 3 3 3 4 8 9 7 1 1 8 5 8 5 7 5 3 0 0 5 5 8 0 0 3 2 5 0 3
 4 3 1 6 9 9 8 2 0 9 7 0 4 3 1 2 4 3 4 7 6 7 5 9 9 0 6 3 1 5 4 5 4 2 9 5 5
 2 9 3 2 4 4 8 2 5 7 8 0 9 1 1 3 7 5 4 9 7 8 4 8 0 5 5 6 3 0 2 6 6 1 5 9 1
 7 7 2 5 9 0 0 6 8 4 0 7 

1112

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [17]:
np_float_arr = np.array([2.4, 5.6, 7.1, 9.5, 3.2], dtype=np.float16)
print(np_float_arr[[0, 2, -1]])

[2.4 7.1 3.2]
<class 'numpy.ndarray'>


## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [18]:
import itertools
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
array[[0, 1, 4, -1]].sum()

27.0

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [19]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [23]:
A.mean(axis=0)

array([2. , 8.4])

### Task 5.2 Get the standard deviation by `y` axis

In [24]:
A.std(axis=1)

array([2.5, 3. , 4. , 3.5, 3. ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [25]:
A.sum(axis=1)

array([ 7, 10, 14, 13,  8])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [27]:
A[:2]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [30]:
A[::2]


array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [39]:
# Python code
[i for i in range(1000000)]

0.0480036735534668 sec


In [12]:
start = time.perf_counter()
np_array = np.array(np.arange(1000000))
end = time.perf_counter()
print(np_array)
print(end - start, "sec")

[     0      1      2 ... 999997 999998 999999]
0.0031946999952197075 sec
CPU times: total: 0 ns
Wall time: 3 ms


### Task 6.2

In [13]:
# Python code
@timeit
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]

unknown_signature(vector1, vector2)



4200 nano-secs


32

In [182]:
# write your numpy code here and estimate the time of execution
@timeit
def vector_multiplication(np_vector1: np.array, np_vector2: np.array):
    result = np_vector1 @ np_vector2
    return result

np_vector1 = np.array([1, 2, 3], dtype=np.int8)
np_vector2 = np.array([4, 5, 6], dtype=np.int8)

vector_multiplication(np_vector1, np_vector2)


19100 nano-secs


32

### Task 6.3

In [197]:
# Python code
@timeit
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2],
           [3, 4]]
matrix2 = [[5, 6], 
           [7, 8]]

unknown_signature(matrix1, matrix2)

6900 nano-secs


[[5, 12], [21, 32]]

In [198]:
# write your numpy code here and estimate the time of execution
@timeit
def matrix_multiplication(np_matrix1, np_matrix2):
    return np_matrix1 * np_matrix2

np_matrix1 = np.array([[1, 2], [3, 4]], dtype=np.int8)
np_matrix2 = np.array([[5, 6], [7, 8]], dtype=np.int8)
matrix_multiplication(np_matrix1, np_matrix2)

11200 nano-secs


array([[ 5, 12],
       [21, 32]], dtype=int8)

### Task 6.4

In [202]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]
unknown_signature(lst)

3.0

In [201]:
# write your numpy code here and estimate the time of execution
@timeit
def get_mean(lst):
    return lst.mean()

lst = np.array([1, 2, 3, 4, 5])

get_mean(lst)

99300 nano-secs


3.0

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [217]:
# Python code
@timeit
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

2700 nano-secs


[0, 2, 0, 4, 0]

In [218]:
# write your numpy code here
np_lst = np.array([1, 2, 3, 4, 5], dtype=np.int8)
start = time.perf_counter_ns()
np_lst[np_lst % 2 != 0] = 0
end = time.perf_counter_ns()
np_lst, end - start

(array([0, 2, 0, 4, 0], dtype=int8), 122100)

### Task 7.2

In [223]:
# Python code
@timeit
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]

result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

7900 nano-secs


([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [222]:
# write your numpy code here
np_array1 = np.array([5, 2, 7, 4, 9], dtype=np.int8)
np_array2 = np.array([3, 6, 1, 8, 10], dtype=np.int8)
start = time.perf_counter_ns() 

np_bw_compl = np.invert(np_array1)
np_and = np.bitwise_and(np_array1, np_array2)
np_or = np.bitwise_or(np_array1, np_array2)

end = time.perf_counter_ns()

np_bw_compl, np_and, np_or, end - start

(array([ -6,  -3,  -8,  -5, -10], dtype=int8),
 array([1, 2, 1, 0, 8], dtype=int8),
 array([ 7,  6,  7, 12, 11], dtype=int8),
 122900)

### Task 7.3 Optional

In [260]:
# Python code
@timeit
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

5700 nano-secs


[3, 13, 11, 21]

In [259]:
# write your numpy code here
my_list_np = np.array([6, 9, 12, 14, 17, 20], dtype=np.int8)
start = time.perf_counter_ns()
result = my_list_np[(my_list_np % 2 == 0) & ((my_list_np % 3 == 0) | (my_list_np > 10))]
end = time.perf_counter_ns()
result = (result ^ 7) + 2
result, end - start


(array([ 3, 13, 11, 21], dtype=int8), 128700)