# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [1]:
import sys
import numpy as np

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [2]:
python_array = [0] * 1000
sys.getsizeof(python_array)

8056

In [3]:
numpy_array = np.array(python_array, dtype=np.int8)
sys.getsizeof(numpy_array)

1112

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [14]:
arr = np.array([.5, .9, 7.3, 1.5, 9.9], dtype=np.float16)
arr[[0, 2, -1]]

array([0.5, 7.3, 9.9], dtype=float16)

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [25]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
array[[0, 1, 4, -1]].sum()

27.0

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [26]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [27]:
A.mean(axis=1)

array([3.5, 5. , 7. , 6.5, 4. ])

### Task 5.2 Get the standard deviation by `y` axis

In [28]:
A.std(axis=0)

array([0.89442719, 1.8547237 ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [29]:
A.sum(axis=0)

array([10, 42])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [30]:
A[:2, :]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [31]:
A[::2, :]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [4]:
%timeit [i for i in range(1000000)]

106 ms ± 10.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
%timeit np.array(np.arange(1000000))

4.64 ms ± 158 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Task 6.2

In [6]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%timeit unknown_signature(vector1, vector2)

771 ns ± 142 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [9]:
vec1 = np.array(vector1)
vec2 = np.array(vector2)
%timeit vec1.dot(vec2)

1.57 µs ± 2.13 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### Task 6.3

In [8]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

%timeit unknown_signature(matrix1, matrix2)

2.1 µs ± 172 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [10]:
mx1 = np.array(matrix1)
mx2 = np.array(matrix2)
%timeit mx1 * mx2

842 ns ± 1.74 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### Task 6.4

In [11]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]

%timeit unknown_signature(lst)

626 ns ± 93.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [12]:
%timeit np.average(lst)

22.6 µs ± 255 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [76]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[0, 2, 0, 4, 0]

In [80]:
new_arr = np.array(lst)
new_arr[mask] = 0
new_arr

array([0, 2, 0, 4, 0])

### Task 7.2

In [81]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [89]:
lst1 = np.array(list1)
lst2 = np.array(list2)
result_bitwise_complement = ~lst1
result_bitwise_and = lst1 & lst2
result_bitwise_or = lst1 | lst2
result_bitwise_complement, result_bitwise_and, result_bitwise_or

(array([ -6,  -3,  -8,  -5, -10]),
 array([1, 2, 1, 0, 8]),
 array([ 7,  6,  7, 12, 11]))

### Task 7.3 Optional

In [102]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [106]:
arr = np.array(my_list)
mask = (arr % 2 == 0) & ((arr % 3 == 0) | (arr > 10))
new_arr = (arr[mask] ^ 7) + 2
new_arr

array([ 3, 13, 11, 21], dtype=int32)

In [107]:
my_array = np.arange(5)
my_array = my_array[[False, True, True, False, True]]

print(my_array[my_array <= True])


[1]
