# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [575]:
import numpy as np

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [576]:
import sys

default_array = [0]*1000
print("Default Python array size: ", sys.getsizeof(default_array), "bytes")

Default Python array size:  8056 bytes


In [577]:
import numpy as np

numpy_array = np.zeros(1000, dtype='int8')
print("Numpy array size: ", numpy_array.nbytes, "bytes")

Numpy array size:  1000 bytes


## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [578]:
import numpy as np

arr = np.array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

print("Array: ", arr)

print("Required elements: ", arr[[0, 2, -1]])

Array:  [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
Required elements:  [0.5 2.5 9.5]


## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [579]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
sum_subsequence = np.sum(array[[0, 1, 4, -1]])
print("Sum of the subsequence: ", sum_subsequence)

Sum of the subsequence:  27.0


## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [580]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [581]:
column_means = A.mean(axis=0)

print("Column means: ", column_means)

Column means:  [2.  8.4]


### Task 5.2 Get the standard deviation by `y` axis

In [582]:
standard_deviation = A.std(axis=1)

print("Column means: ", standard_deviation)

Column means:  [2.5 3.  4.  3.5 3. ]


### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [583]:
row_sums = A.sum(axis=1)
print("Row sums: ", row_sums)

Row sums:  [ 7 10 14 13  8]


### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [584]:
result = A[:2]
print(result)

[[1 6]
 [2 8]]


##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [585]:
result = A[::2]
print(result)

[[ 1  6]
 [ 3 11]
 [ 1  7]]


## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [586]:
import time
start_time = time.time()
lst = [i for i in range(1000000)]
end_time = time.time()
python_exec_time = end_time - start_time
print("Time using standard Python: ", python_exec_time)

Time using standard Python:  0.044196367263793945


In [616]:
start_time = time.time()
np_arr = np.arange(1000000)
end_time = time.time()
numpy_exec_time = end_time - start_time
print('Time using Numpy: ', numpy_exec_time)

Time using Numpy:  0.015617609024047852


### Task 6.2

In [628]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
%timeit unknown_signature(vector1, vector2)
result = unknown_signature(vector1, vector2)
print("The result is:", result)

356 ns ± 59.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
The result is: 32


In [629]:
vector1_np = np.array(vector1)
vector2_np = np.array(vector2)
%timeit np.dot(vector1_np, vector2_np)
result_numpy = np.dot(vector1_np, vector2_np)
print("The result is:", result_numpy)

1.05 µs ± 6.54 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
The result is: 32


### Task 6.3

In [630]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

%timeit unknown_signature(matrix1, matrix2)
result = unknown_signature(matrix1, matrix2)
print("The result is:", result)

865 ns ± 16 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
The result is: [[5, 12], [21, 32]]


In [631]:
matrix1_np = np.array(matrix1)
matrix2_np = np.array(matrix2)
%timeit matrix1_np * matrix2_np
result_np = matrix1_np * matrix2_np
print("The result is:", result_np)

527 ns ± 8.05 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
The result is: [[ 5 12]
 [21 32]]


### Task 6.4

In [632]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]

%timeit unknown_signature(lst)
result = unknown_signature(lst)
print("The result is:", result)

261 ns ± 52.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
The result is: 3.0


In [635]:
lst_np = np.array(lst)
%timeit np.mean(lst_np)
result_np = np.mean(lst_np)
print("The result is:", result_np)

4.63 µs ± 6.54 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
The result is: 3.0


## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [637]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[0, 2, 0, 4, 0]

In [639]:
lst_np = np.array(lst, dtype=np.int8)
mask_np = np.array([True, False, True, False, True])
new_value_np = 0
lst_np[mask_np] = new_value_np
lst_np

array([0, 2, 0, 4, 0], dtype=int8)

### Task 7.2

In [596]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [641]:
def unknown_signature(lst1, lst2):
    lst1_np = np.array(lst1)
    lst2_np = np.array(lst2)
    
    bitwise_complement = ~lst1_np
    bitwise_and = lst1_np & lst2_np
    bitwise_or = lst1_np | lst2_np
    
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

(array([ -6,  -3,  -8,  -5, -10]),
 array([1, 2, 1, 0, 8]),
 array([ 7,  6,  7, 12, 11]))

### Task 7.3 Optional

In [598]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [642]:
def unknown_signature(lst):
    lst_np = np.array(lst)
    mask_np = (lst_np % 2 == 0) & ((lst_np % 3 == 0) | (lst_np > 10))
    lst_np[mask_np] = (lst_np[mask_np] ^ 7) + 2
    return lst_np[mask_np]
        
my_list = [6, 9, 12, 14, 17, 20]
result_numpy_style = unknown_signature(my_list)
result_numpy_style

array([ 3, 13, 11, 21])