# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [5]:
import numpy as np
# import numpy as np
import pandas as pd
import sys
import time
import random




## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [10]:
num = 0
size = 1000
list_of_zeros = [num for _ in range(size)]
sys.getsizeof(list_of_zeros)

8856

In [13]:
np_array = np.array(list_of_zeros, dtype=np.int8)
sys.getsizeof(np_array)

1112

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [19]:
np_array_two = np.array([9.0, 2.2, 4, 9, 8.8, 6.6, 3.3])
np_array_two[[1, 2, -1]]

array([2.2, 4. , 3.3])

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [67]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
np.sum(array[[4, -1, 3, 2, 4]])

27.0

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [37]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [52]:
for x in A:
    print(np.sum(x))

7
10
14
13
8


### Task 5.2 Get the standard deviation by `y` axis

In [65]:
np.std(A[:, :1]), np.std(A[:, 1]), np.std(A[:, :2])

(0.8944271909999159, 1.8547236990991407, 3.515679166249389)

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [75]:
np.sum(A[:, :1]), np.sum(A[:, 1]), np.sum(A[:, :2]), A.sum(axis=0)

(10, 42, 52, array([10, 42]))

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [72]:
A[:2, :]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [76]:
A[[0, 2, 4], :]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [2]:
# Python code
begin_timer = time.time()
array = [i for i in range(1000000)]
end_timer = time.time()
estimated_time = end_timer - begin_timer
print(estimated_time)


0.03503227233886719


In [3]:
# write your numpy code here and estimate the time of execution
begin_timer = time.time()
numpy_arr = np.arange(1000000)
end_timer = time.time()
estimated_time = end_timer - begin_timer
print(estimated_time)

0.0009989738464355469


### Task 6.2

In [125]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

begin = time.perf_counter_ns()
vector1 = [1, 2, 3]
vector2 = [4, 5, 6]


result = unknown_signature(vector1, vector2)
end = time.perf_counter_ns()

estimated_time_q = end - begin

result, estimated_time_q



(32, 130400)

In [108]:
# write your numpy code here and estimate the time of execution
begin = time.perf_counter_ns()
a = np.array([1, 2, 3], dtype=np.int8)
b = np.array([4, 5, 6], dtype=np.int8)
result = np.dot(a, b)
end = time.perf_counter_ns()
timer = end - begin
result, timer



(32, 118800)

## Task 6.3

In [133]:
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]
result = unknown_signature(matrix1, matrix2)
result

[[5, 12], [21, 32]]

In [171]:
A = np.array(matrix1, dtype=np.int8)
B = np.array(matrix2, dtype=np.int8)
result = np.multiply(A,B)
result

array([[ 5, 12],
       [21, 32]], dtype=int8)

### Task 6.4

In [173]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]
result = unknown_signature(lst)
result

3.0

In [249]:
np_array = np.array([1, 2, 3, 4, 5], dtype=np.int8)
np_array.mean(), sys.getsizeof(np_array)

(3.0, 117, 104, array([1, 2, 3, 4, 5], dtype=int8))

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [203]:
# Python code
def unknown_signature(lst, mask, new_value):
    new_lst = lst[:]
    for i in range(len(lst)):
        if mask[i]:
            new_lst[i] = new_value
    return new_lst

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
new_lst = unknown_signature(lst, mask, new_value)
lst, new_lst

([1, 2, 3, 4, 5], [0, 2, 0, 4, 0])

In [225]:
LST = np.array(lst)
MUSK = np.array(mask)
NEW_LST = np.where(MUSK, new_value, LST)
LST, NEW_LST

(array([1, 2, 3, 4, 5]), array([0, 2, 0, 4, 0]))

### Task 7.2

In [214]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [259]:
A = np.array([5, 2, 7, 4, 9], dtype=np.int8)
B = np.array([3, 6, 1, 8, 10], dtype=np.int8)
print(B)
bc = np.bitwise_not(A)
ba = np.bitwise_and(B, A)
bo = np.bitwise_or(A, B)


bc, ba, bo

[ 3  6  1  8 10]


(array([ -6,  -3,  -8,  -5, -10], dtype=int8),
 array([1, 2, 1, 0, 8], dtype=int8),
 array([ 7,  6,  7, 12, 11], dtype=int8))

### Task 7.3 Optional

In [230]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [35]:
# write your numpy code here