# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [2]:
import sys
import numpy as np

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [3]:
python_array = [0] * 1000
print(sys.getsizeof(python_array))

8056


In [4]:
numpy_array = np.zeros(1000, dtype=np.int8)
print(sys.getsizeof(numpy_array))

1112


## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [5]:
float_array = np.random.uniform(0, 10.0, size=np.random.randint(5, 11))
float_array[[0, 2, -1]]

array([5.98824118, 8.49115146, 1.19657301])

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [130]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
result_sum = int(np.sum(array[[1, 2, 3, 4, 5]]))
result_sum

27

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [9]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [10]:
column_means = np.mean(A, axis=1)
print(column_means)

[3.5 5.  7.  6.5 4. ]


### Task 5.2 Get the standard deviation by `y` axis

In [11]:
row_std = np.std(A, axis=0)
print(row_std)

[0.89442719 1.8547237 ]


### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [132]:
all_sum = np.sum(A, axis=1)
print(all_sum)

[ 7 10 14 13  8]


### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [137]:
print(A[[0, 1]])

[[1 6]
 [2 8]]


##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [43]:
print(A[[0, 2, 4]])

[[ 1  6]
 [ 3 11]
 [ 1  7]]


## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [61]:
# Python code
%timeit [i for i in range(1000000)]

20.5 ms ± 77 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [62]:
%timeit np.arange(1000000)

673 µs ± 21.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### Task 6.2

In [128]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = unknown_signature(vector1, vector2)

%time unknown_signature(vector1, vector2)
result

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 5.72 µs


32

In [104]:
def unknown_signature(vector1, vector2):
    return vector1 @ vector2

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
result = unknown_signature(vector1, vector2)

%time unknown_signature(vector1, vector2)
result

CPU times: user 5 µs, sys: 1 µs, total: 6 µs
Wall time: 6.91 µs


32

### Task 6.3

In [140]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

result = unknown_signature(matrix1, matrix2)

%time unknown_signature(matrix1, matrix2)
result

CPU times: user 8 µs, sys: 1 µs, total: 9 µs
Wall time: 11 µs


[[5, 12], [21, 32]]

In [143]:
def unknown_signature(matrix1, matrix2):
    result = matrix1 * matrix2
    return result.tolist()

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = unknown_signature(matrix1, matrix2)

%time unknown_signature(matrix1, matrix2)
result

CPU times: user 6 µs, sys: 1 µs, total: 7 µs
Wall time: 10 µs


[[5, 12], [21, 32]]

### Task 6.4

In [162]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]

result = unknown_signature(lst)

%time unknown_signature(lst)
result

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 6.91 µs


3.0

In [201]:
def unknown_signature(lst):
    return np.mean(lst)

lst = np.array([1, 2, 3, 4, 5])

result = unknown_signature(lst)

%time unknown_signature(lst)
result

CPU times: user 17 µs, sys: 1e+03 ns, total: 18 µs
Wall time: 23.1 µs


3.0

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [220]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
%time unknown_signature(lst, mask, new_value)
lst

CPU times: user 5 µs, sys: 0 ns, total: 5 µs
Wall time: 7.15 µs


[0, 2, 0, 4, 0]

In [208]:
def unknown_signature(lst, mask, new_value):
    lst[mask] = new_value
    return lst.tolist()

lst = np.array([1, 2, 3, 4, 5])
mask = [True, False, True, False, True]
new_value = 0
result = unknown_signature(lst, mask, new_value)
%time unknown_signature(lst, mask, new_value)
result

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 5.96 µs


[0, 2, 0, 4, 0]

### Task 7.2

In [239]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
%time unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

CPU times: user 6 µs, sys: 0 ns, total: 6 µs
Wall time: 14.1 µs


([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [228]:
def unknown_signature(lst1, lst2):
    bitwise_complement = ~lst1
    bitwise_and = np.bitwise_and(lst1, lst2)
    bitwise_or = np.bitwise_or(lst1, lst2)
    return bitwise_complement.tolist(), bitwise_and.tolist(), bitwise_or.tolist()


list1 = np.array([5, 2, 7, 4, 9])
list2 = np.array([3, 6, 1, 8, 10])
%time unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

CPU times: user 22 µs, sys: 0 ns, total: 22 µs
Wall time: 24.1 µs


([False, False, False, False, False], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

### Task 7.3 Optional

In [223]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
%time unknown_signature(my_list)
result_python_style = unknown_signature(my_list)
result_python_style

CPU times: user 7 µs, sys: 0 ns, total: 7 µs
Wall time: 10 µs


[3, 13, 11, 21]

In [238]:
def unknown_signature(lst):
    mask = (lst % 2 == 0) & ((lst % 3 == 0) | (lst > 10))
    modified_nums = (lst[mask] ^ 7) + 2
    return modified_nums.tolist()

my_list = np.array([6, 9, 12, 14, 17, 20])
%time unknown_signature(my_list)
result_python_style = unknown_signature(my_list)
result_python_style

CPU times: user 55 µs, sys: 1 µs, total: 56 µs
Wall time: 57.7 µs


[3, 13, 11, 21]