# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [2]:
import numpy as np
import sys

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [3]:
python_array = [0] * 1000

In [10]:
numpy_array = np.array([0] * 1000, dtype=np.int8)
print("Size of Python:", sys.getsizeof(python_array), "bytes")
print("Size of NP:", numpy_array.nbytes, "bytes")

Size of Python: 8056 bytes
Size of NP: 1000 bytes


## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [11]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
array[[0, 2, -1]]

array([ 2.3,  3.2, 11.1])

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [3]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])

result = np.sum(array[[0, 1, 4, -1]])

print(result)

27.0


## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [20]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [22]:
column_means = np.mean(A, axis=0)
column_means

array([2. , 8.4])

### Task 5.2 Get the standard deviation by `y` axis

In [23]:
std_dev = np.std(A, axis=1)
std_dev

array([2.5, 3. , 4. , 3.5, 3. ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [24]:
sum = np.sum(A, axis=1)
sum

array([ 7, 10, 14, 13,  8])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [25]:
result = A[:2]
result

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [27]:
result = A[[0, 2, 4]]
result

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [30]:
import time
start_time = time.time()
[i for i in range(1000000)]
end_time = time.time()
print("Py time:", end_time - start_time, "sec")


Py time: 0.03554892539978027 sec


In [5]:
import time

start_time = time.time()
np_result = np.arange(1000000)
end_time = time.time()

print("NP time:", end_time - start_time, "sec")

NP time: 0.001934051513671875 sec


### Task 6.2

In [31]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%time unknown_signature(vector1, vector2)
result

CPU times: user 5 µs, sys: 3 µs, total: 8 µs
Wall time: 14.1 µs


0

In [6]:
np_vector1 = np.array([1, 2, 3])
np_vector2 = np.array([4, 5, 6])

start_time = time.time()
np_result = np_vector1 @ np_vector2
end_time = time.time()

print("numpy time:", end_time - start_time, "sec")
np_result

numpy time: 0.0005161762237548828 sec


32

### Task 6.3

In [26]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

In [35]:
matrix1_np = np.array([[1, 2], [3, 4]])
matrix2_np = np.array([[5, 6], [7, 8]])

start_time = time.time()
np_result = np.multiply(matrix1_np, matrix2_np)
end_time = time.time()

print("numpy time:", end_time - start_time, "sec")
np_result

numpy time: 7.128715515136719e-05 sec


array([[ 5, 12],
       [21, 32]])

### Task 6.4

In [ ]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]

In [36]:
lst_np = np.array([1, 2, 3, 4, 5])

start_time = time.time()
np_result = np.mean(lst_np)
end_time = time.time()

print("numpy time:", end_time - start_time, "sec")
np_result

numpy time: 0.0011398792266845703 sec


3.0

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [31]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[0, 2, 0, 4, 0]

In [37]:
lst = np.array([1, 2, 3, 4, 5])
mask = np.array([True, False, True, False, True])
new_value = 0

lst[mask] = new_value
lst

array([0, 2, 0, 4, 0])

### Task 7.2

In [38]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [39]:
list1_np = np.array([5, 2, 7, 4, 9])
list2_np = np.array([3, 6, 1, 8, 10])

result_bitwise_complement_np = np.bitwise_not(list1_np)
result_bitwise_and_np = np.bitwise_and(list1_np, list2_np)
result_bitwise_or_np = np.bitwise_or(list1_np, list2_np)

result_bitwise_complement_np.tolist(), result_bitwise_and_np.tolist(), result_bitwise_or_np.tolist()

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

### Task 7.3 Optional

In [34]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [35]:
# write your numpy code here