# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [3]:
import sys
import numpy as np

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [3]:
array = [0] * 1000
sys.getsizeof(array)

8056

In [4]:
array = np.zeros(1000, dtype=int)
sys.getsizeof(array)

4112

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [7]:
array = np.array([.5, 4.6, 7.7, 1.1, 5, 2.3, .1, .0, 1.2], dtype="float16")
array[[0, 2, -1]]

array([0.5, 7.7, 1.2], dtype=float16)

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [8]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
array[-3:-1].sum()

27.1

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [10]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [11]:
np.mean(A, axis=0)

array([2. , 8.4])

### Task 5.2 Get the standard deviation by `y` axis

In [12]:
np.std(A, axis=1)

array([2.5, 3. , 4. , 3.5, 3. ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [13]:
np.sum(A, axis=1)

array([ 7, 10, 14, 13,  8])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [14]:
A[:2, :]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [15]:
A[0::2, :]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [1]:
%timeit [i for i in range(1000000)]

59.2 ms ± 2.01 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
%timeit np.arange(1000000, dtype=int)

1.43 ms ± 42.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### Task 6.2

In [35]:
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%timeit unknown_signature(vector1, vector2)
result

CPU times: total: 0 ns
Wall time: 0 ns


0

In [36]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
%timeit (vector1 * vector2).sum()

CPU times: total: 0 ns
Wall time: 0 ns


32

### Task 6.3

In [37]:
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]
unknown_signature(matrix1, matrix2)

[[5, 12], [21, 32]]

In [39]:
matrix1 = np.matrix([[1, 2], [3, 4]])
matrix2 = np.matrix([[5, 6], [7, 8]])
%timeit np.multiply(matrix1, matrix2)

CPU times: total: 0 ns
Wall time: 0 ns


matrix([[ 5, 12],
        [21, 32]])

### Task 6.4

In [40]:
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]
%timeit unknown_signature(lst)

CPU times: total: 0 ns
Wall time: 0 ns


3.0

In [41]:
lst = np.array([1, 2, 3, 4, 5])
%timeit np.mean(lst)

CPU times: total: 0 ns
Wall time: 0 ns


3.0

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [31]:
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[0, 2, 0, 4, 0]

In [43]:
lst = np.array([1, 2, 3, 4, 5])
%timeit np.where([True, False, True, False, True], 0, lst)


CPU times: total: 0 ns
Wall time: 0 ns


array([0, 2, 0, 4, 0])

### Task 7.2

In [48]:
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
%timeit result_bitwise_complement, result_bitwise_and, result_bitwise_or

CPU times: total: 0 ns
Wall time: 0 ns


([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [51]:
list1 = np.array([5, 2, 7, 4, 9])
list2 = np.array([3, 6, 1, 8, 10])
%timeit np.invert(list1), np.bitwise_and(list1, list2), np.bitwise_or(list1, list2)

CPU times: total: 0 ns
Wall time: 0 ns


(array([ -6,  -3,  -8,  -5, -10]),
 array([1, 2, 1, 0, 8]),
 array([ 7,  6,  7, 12, 11]))

### Task 7.3 Optional

In [56]:
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [67]:
my_list = np.array([6, 9, 12, 14, 17, 20])
mask = (my_list % 2 == 0) & ((my_list % 3 == 0) | (my_list > 10))
new_list = (my_list ^ 7) + 2
result = new_list[mask]
result

array([ 3, 13, 11, 21], dtype=int32)