# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [2]:
import numpy as np
import sys

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [9]:
array_python = [0] * 1000
print("Size of array_python:", sys.getsizeof(array_python), "bytes")

Size of array_python: 8056 bytes


In [10]:
array_numpy = np.zeros(1000, dtype=np.int8)
print("Size of array_numpy:", array_numpy.nbytes, "bytes")

Size of array_numpy: 1000 bytes


## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [11]:
import numpy as np

float_array = np.array([1.2, 3.5, 5.1, 6.3, 7.7])
indexes = float_array[[0, 2, -1]]
indexes

array([1.2, 5.1, 7.7])

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [18]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
indices = np.array([0, 1, 4, -1])
result = np.sum(array[indices])
result

27.0

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [ ]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [26]:
A.mean(axis=1)

array([3.5, 5. , 7. , 6.5, 4. ])

### Task 5.2 Get the standard deviation by `y` axis

In [27]:
A.std(axis=0)

array([0.89442719, 1.8547237 ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [29]:
A.sum(axis=0)

array([10, 42])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [30]:
A[:2, :]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [32]:
A[::2]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [34]:
from time import time

start_time = time()
[i for i in range(1000000)]
end_time = time() - start_time
end_time

0.11974072456359863

In [42]:
from time import time

start_time = time()
np.arange(1000000)
end_time = time() - start_time
end_time

CPU times: total: 0 ns
Wall time: 2.01 ms


array([     0,      1,      2, ..., 999997, 999998, 999999])

### Task 6.2

In [47]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%time unknown_signature(vector1, vector2)
result

CPU times: total: 0 ns
Wall time: 0 ns


0

In [49]:
vector1_np = np.array([1, 2, 3])
vector2_np = np.array([4, 5, 6])
%time np.dot(vector1, vector2)


CPU times: total: 0 ns
Wall time: 0 ns


32

### Task 6.3

In [26]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

In [53]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
%time matrix1 * matrix2

CPU times: total: 0 ns
Wall time: 0 ns


array([[ 5, 12],
       [21, 32]])

### Task 6.4

In [57]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]

3.0

In [59]:
np_array = np.array([1, 2, 3, 4, 5])
%time np.average(np_array)

CPU times: total: 0 ns
Wall time: 0 ns


3.0

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [31]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[0, 2, 0, 4, 0]

In [60]:
def unknown_signature_np(lst, mask, new_value):
    lst_np = np.array(lst)
    mask_np = np.array(mask)
    lst_np[mask_np] = new_value
    return lst_np.tolist()

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0

result_np = unknown_signature_np(lst, mask, new_value)
result_np

[0, 2, 0, 4, 0]

### Task 7.2

In [62]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [61]:
def unknown_signature_np(lst1, lst2):
    bitwise_complement = np.invert(lst1)
    bitwise_and = np.bitwise_and(lst1, lst2)
    bitwise_or = np.bitwise_or(lst1, lst2)
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]

result_bitwise_complement_np, result_bitwise_and_np, result_bitwise_or_np = unknown_signature_np(np.array(list1), np.array(list2))
result_bitwise_complement_np, result_bitwise_and_np, result_bitwise_or_np

(array([ -6,  -3,  -8,  -5, -10]),
 array([1, 2, 1, 0, 8]),
 array([ 7,  6,  7, 12, 11]))

### Task 7.3 Optional

In [34]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [63]:
def unknown_signature_np(lst):
    lst_np = np.array(lst)
    mask = (lst_np % 2 == 0) & ((lst_np % 3 == 0) | (lst_np > 10))
    modified_num = (lst_np[mask] ^ 7) + 2
    return modified_num.tolist()

my_list = [6, 9, 12, 14, 17, 20]
result_numpy_style = unknown_signature_np(my_list)
result_numpy_style

[3, 13, 11, 21]