# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [1]:
import numpy as np
import sys

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [2]:
python_array = [0] * 1000
sys.getsizeof(python_array)

8056

In [3]:
numpy_array = np.zeros(1000, dtype=np.int8)
sys.getsizeof(numpy_array)

1112

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [4]:
float_array = np.arange(0, 11, dtype=float)
float_array[[0, 2, -1]]

array([ 0.,  2., 10.])

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [5]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
array[[1, 7, 4, 0]].sum()

27.0

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [6]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [7]:
np.mean(A, axis=1)

array([3.5, 5. , 7. , 6.5, 4. ])

### Task 5.2 Get the standard deviation by `y` axis

In [8]:
np.std(A, axis=0)

array([0.89442719, 1.8547237 ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [9]:
np.sum(A, axis=0)

array([10, 42])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [10]:
A[:2]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [11]:
A[[0, 2, 4]]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [12]:
# Python code
%timeit [i for i in range(1000000)]

96.2 ms ± 12.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
%timeit np.arange(1000000, dtype=np.int8)

988 µs ± 50.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### Task 6.2

In [14]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%timeit unknown_signature(vector1, vector2)
result

425 ns ± 12.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


0

In [15]:
def unknown_signature_np(vector1, vector2):
    result = np.dot(vector1, vector2)
    return result

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

%timeit unknown_signature_np(vector1, vector2)
unknown_signature_np(vector1, vector2)


2.95 µs ± 810 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


32

### Task 6.3

In [16]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

%timeit unknown_signature(matrix1, matrix2)
result

1.49 µs ± 273 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


0

In [17]:
def unknown_signature_np(matrix1, matrix2):
    result = np.multiply(matrix1, matrix2)
    return result.tolist()

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

%timeit unknown_signature_np(matrix1, matrix2)
unknown_signature_np(matrix1, matrix2)

1.3 µs ± 247 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


[[5, 12], [21, 32]]

### Task 6.4

In [18]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]

%timeit unknown_signature(lst)
result

338 ns ± 18.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


0

In [19]:
def unknown_signature_np(lst):
    result = np.mean(lst)
    return result

lst = np.array([1, 2, 3, 4, 5])

%timeit unknown_signature_np(lst)
unknown_signature_np(lst)

10.6 µs ± 631 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


3.0

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [20]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0

%timeit unknown_signature(lst, mask, new_value)
lst

677 ns ± 49.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


[0, 2, 0, 4, 0]

In [22]:
def unknown_signature_np(lst, mask, new_value):
    lst = np.array(lst)
    lst[mask] = new_value
    return lst.tolist()

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0

%timeit unknown_signature_np(lst, mask, new_value)
unknown_signature_np(lst, mask, new_value)

6.18 µs ± 366 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


[0, 2, 0, 4, 0]

### Task 7.2

In [23]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]

result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
%timeit result_bitwise_complement, result_bitwise_and, result_bitwise_or

87 ns ± 4.99 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [27]:
def unknown_signature_np(lst1, lst2):   
    bitwise_complement = np.bitwise_not(lst1)
    bitwise_and = np.bitwise_and(lst1, lst2)
    bitwise_or = np.bitwise_or(lst1, lst2)
    return bitwise_complement, bitwise_and, bitwise_or

list1 = np.array([5, 2, 7, 4, 9])
list2 = np.array([3, 6, 1, 8, 10])

%timeit unknown_signature_np(list1, list2)
unknown_signature_np(list1, list2)

4.31 µs ± 693 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


(array([ -6,  -3,  -8,  -5, -10]),
 array([1, 2, 1, 0, 8]),
 array([ 7,  6,  7, 12, 11]))

### Task 7.3 Optional

In [26]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
%timeit result_python_style

16.5 ns ± 0.227 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [28]:
def unknown_signature_np(lst):
    lst = np.array(lst)
    mask = np.logical_and(lst % 2 == 0, np.logical_or(lst % 3 == 0, lst > 10))
    modified_nums = (np.bitwise_xor(lst[mask], 7) + 2).tolist()
    return modified_nums

my_list = [6, 9, 12, 14, 17, 20]
%timeit unknown_signature_np(my_list)
unknown_signature_np(my_list)

36.5 µs ± 7.34 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


[3, 13, 11, 21]