# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [36]:
import numpy as np
import sys

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [37]:
python_array = [0] * 1000
sys.getsizeof(python_array)

8056

In [38]:
numpy_array = np.zeros(1000, int)

sys.getsizeof(numpy_array)

4112

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [39]:
float_array = np.arange(0, 11, dtype=float)
float_array[[0, 2, -1]]

array([0.0, 2.0, 10.0])

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [41]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
np.sum(array[[(2, 3), (4, 6)]])

27.700000000000003

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [42]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [43]:
np.mean(A, axis=0)

array([2.0, 8.4])

### Task 5.2 Get the standard deviation by `y` axis

In [44]:
np.std(A, axis=1)

array([2.5, 3.0, 4.0, 3.5, 3.0])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [45]:
np.sum(A, axis=1)

array([ 7, 10, 14, 13,  8])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [46]:
A[:2]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [47]:
A[[0, 2, 4]]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [52]:
# Python code
%timeit [i for i in range(1000000)]

52.4 ms ± 4.63 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [53]:
%timeit np.arange(1000000, dtype=int)

1.2 ms ± 3.96 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### Task 6.2

In [55]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%timeit unknown_signature(vector1, vector2)
result

349 ns ± 2.31 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


0

In [56]:
def unknown_signature_np(vector1, vector2):
    result = np.dot(vector1, vector2)
    return result

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

%timeit unknown_signature_np(vector1, vector2)
result


1.26 µs ± 18.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


0

### Task 6.3

In [57]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

%timeit unknown_signature(matrix1, matrix2)
result

918 ns ± 14.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


0

In [59]:
def unknown_signature_np(matrix1, matrix2):
    result = np.multiply(matrix1, matrix2)
    return result.tolist()

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

%timeit unknown_signature_np(matrix1, matrix2)
result

898 ns ± 54.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


0

### Task 6.4

In [61]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]

%timeit unknown_signature(lst)
result

381 ns ± 160 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


0

In [63]:
def unknown_signature_np(lst):
    result = np.mean(lst)
    return result

lst = np.array([1, 2, 3, 4, 5])

%timeit unknown_signature_np(lst)
result

5.48 µs ± 134 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


0

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [64]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0

%timeit unknown_signature(lst, mask, new_value)
lst

365 ns ± 41.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


[0, 2, 0, 4, 0]

In [65]:
def unknown_signature_np(lst, mask, new_value):
    lst = np.array(lst)
    lst[mask] = new_value
    return lst.tolist()

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0

%timeit unknown_signature(lst, mask, new_value)
lst

354 ns ± 7.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


[0, 2, 0, 4, 0]

### Task 7.2

In [67]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]

result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
%timeit result_bitwise_complement, result_bitwise_and, result_bitwise_or

43.3 ns ± 2.72 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [68]:
def unknown_signature_np(lst1, lst2):   
    bitwise_complement = np.bitwise_not(lst1)
    bitwise_and = np.bitwise_and(lst1, lst2)
    bitwise_or = np.bitwise_or(lst1, lst2)
    return bitwise_complement, bitwise_and, bitwise_or

list1 = np.array([5, 2, 7, 4, 9])
list2 = np.array([3, 6, 1, 8, 10])

result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
%timeit result_bitwise_complement, result_bitwise_and, result_bitwise_or

43.4 ns ± 0.483 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


### Task 7.3 Optional

In [69]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
%timeit result_python_style

17.4 ns ± 1.35 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [71]:
def unknown_signature_np(lst):
    lst = np.array(lst)
    mask = np.logical_and(lst % 2 == 0, np.logical_or(lst % 3 == 0, lst > 10))
    modified_nums = (np.bitwise_xor(lst[mask], 7) + 2).tolist()
    return modified_nums

my_list = [6, 9, 12, 14, 17, 20]
result_numpy_style = unknown_signature_np(my_list)
%timeit result_numpy_style

16 ns ± 0.151 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)
