# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [27]:
import numpy as np
import sys

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [28]:
py_list = [0] * 1000
sys.getsizeof(py_list)

8056

In [29]:
numpy_arr = np.array(py_list, dtype=np.int8)
sys.getsizeof(numpy_arr)

1112

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [30]:
array = np.array([1, 2.4, 5, .6, 9, 3, 8, 5.7, 9.2], dtype=np.float16)
array[[0, 2, -1]]

array([1. , 5. , 9.2], dtype=float16)

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [31]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
array[[1, 7, 4, 0]].sum()

27.0

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [34]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [35]:
A.mean(axis=1)

array([3.5, 5. , 7. , 6.5, 4. ])

### Task 5.2 Get the standard deviation by `y` axis

In [36]:
A.std(axis=0)

array([0.89442719, 1.8547237 ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [37]:
A.sum(axis=0)

array([10, 42])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [38]:
A[[0, 1]]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [39]:
A[::2]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [40]:
# Python code
%timeit [i for i in range(1000000)]

59.5 ms ± 2.92 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [41]:
%timeit np.arange(1000000)

1.38 ms ± 36 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### Task 6.2

In [44]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%timeit unknown_signature(vector1, vector2)
unknown_signature(vector1, vector2)

385 ns ± 5.04 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


32

In [46]:
def dot_vectors(vector1, vector2):
    return np.dot(np.array(vector1, dtype=np.int8), np.array(vector2, dtype=np.int8))

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]

%timeit dot_vectors(vector1, vector2)
dot_vectors(vector1, vector2)

2.74 µs ± 552 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


32

### Task 6.3

In [48]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

%timeit unknown_signature(matrix1, matrix2)
unknown_signature(matrix1, matrix2)

1.02 µs ± 20.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


[[5, 12], [21, 32]]

In [49]:
def multiply_matrix(matrix1, matrix2):
    return np.multiply(np.array(matrix1, dtype=np.int8), np.array(matrix2, dtype=np.int8))

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

%timeit multiply_matrix(matrix1, matrix2)
multiply_matrix(matrix1, matrix2)

3.62 µs ± 1.56 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


array([[ 5, 12],
       [21, 32]], dtype=int8)

### Task 6.4

In [50]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]

%timeit unknown_signature(lst)
unknown_signature(lst)

320 ns ± 96.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


3.0

In [51]:
def mean_list(lst):
    return np.mean(np.array(lst, dtype=np.int8))

lst = [1, 2, 3, 4, 5]

%timeit mean_list(lst)
mean_list(lst)

7.29 µs ± 128 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


3.0

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [52]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
%timeit unknown_signature(lst, mask, new_value)
lst

392 ns ± 2.57 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


[0, 2, 0, 4, 0]

In [54]:
def replace_list(lst, mask, new_value):
    lst = np.array(lst, dtype=np.int8)
    lst[mask] = new_value
    return lst

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0

%timeit replace_list(lst, mask, new_value)
replace_list(lst, mask, new_value)

3 µs ± 1.24 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


array([0, 2, 0, 4, 0], dtype=int8)

### Task 7.2

In [65]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
%timeit unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

1.73 µs ± 7.63 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [66]:
def change_lists(lst1, lst2):
    lst1 = np.array(lst1, dtype=np.int8)
    lst2 = np.array(lst2, dtype=np.int8)
    
    bitwise_complement = ~lst1
    bitwise_and = lst1 & lst2
    bitwise_or = lst1 | lst2
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]

%timeit change_lists(list1, list2)
change_lists(list1, list2)

3.16 µs ± 23.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


(array([ -6,  -3,  -8,  -5, -10], dtype=int8),
 array([1, 2, 1, 0, 8], dtype=int8),
 array([ 7,  6,  7, 12, 11], dtype=int8))

### Task 7.3 Optional

In [67]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
%timeit unknown_signature(my_list)
unknown_signature(my_list)

768 ns ± 21.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


[3, 13, 11, 21]

In [68]:
def list_mat_operations(lst):
    lst = np.array(lst, dtype=np.int8)
    return [(num ^ 7) + 2 for num in lst if num % 2 == 0 & (num % 3 == 0 | num > 10)]

my_list = [6, 9, 12, 14, 17, 20]
%timeit list_mat_operations(my_list)
list_mat_operations(my_list)

50.3 µs ± 230 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


[3, 13, 11, 21]