# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [1]:
import sys
import numpy as np

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [2]:
a = [0] * 1000
sys.getsizeof(a)

8056

In [44]:
arr = np.zeros(1000, dtype=np.int8)
sys.getsizeof(arr)

1112

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [8]:
array_length = np.random.randint(5, 11)
float_array = np.random.uniform(0, 10, array_length)
float_array[[0, 2, -1]]

array([2.27914378, 8.05295427, 2.96757591])

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [66]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
array[[0, 1, 4, 7]].sum()

27.0

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [18]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [46]:
A.mean(axis=1)

array([3.5, 5. , 7. , 6.5, 4. ])

### Task 5.2 Get the standard deviation by `y` axis

In [48]:
A.std(axis=0)

array([0.89442719, 1.8547237 ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [49]:
A.sum(axis=0)

array([10, 42])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [50]:
A[:2, :2]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [51]:
A[[0, 2, -1], :2]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [53]:
import time

start_time = time.time()
py_list = [i for i in range(1000000)]
end_time = time.time()
py_execution_time = end_time - start_time
py_execution_time

0.107086181640625

In [54]:
start_time = time.time()
np.arange(1000000)
end_time = time.time()
np_execution_time = end_time - start_time
np_execution_time

0.0026540756225585938

### Task 6.2

In [61]:
vector1 = [1, 2, 3]
vector2 = [4, 5, 6]

%time result = sum(x * y for x, y in zip(vector1, vector2))


CPU times: total: 0 ns
Wall time: 0 ns


In [62]:
%time np.dot(vector1, vector2)


CPU times: total: 0 ns
Wall time: 0 ns


32

### Task 6.3

In [59]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]
%time unknown_signature(matrix1, matrix2)

CPU times: total: 0 ns
Wall time: 0 ns


[[5, 12], [21, 32]]

In [60]:
%time np.multiply(matrix1, matrix2)

CPU times: total: 0 ns
Wall time: 0 ns


array([[ 5, 12],
       [21, 32]])

### Task 6.4

In [64]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]
%time unknown_signature(lst)

CPU times: total: 0 ns
Wall time: 0 ns


3.0

In [65]:
%time np.mean(lst)

CPU times: total: 0 ns
Wall time: 0 ns


3.0

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [39]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[0, 2, 0, 4, 0]

In [41]:
lst = np.array([1, 2, 3, 4, 5])
mask = np.array([True, False, True, False, True])
new_value = 0
lst[mask] = new_value
lst

array([0, 2, 0, 4, 0])

### Task 7.2

In [33]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

In [42]:
list1 = np.array([5, 2, 7, 4, 9])
list2 = np.array([3, 6, 1, 8, 10])

result_bitwise_complement = ~list1
result_bitwise_and = list1 & list2
result_bitwise_or = list1 | list2

(result_bitwise_complement, result_bitwise_and, result_bitwise_or)

(array([ -6,  -3,  -8,  -5, -10]),
 array([1, 2, 1, 0, 8]),
 array([ 7,  6,  7, 12, 11]))

### Task 7.3 Optional

In [34]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [43]:
my_list = np.array([6, 9, 12, 14, 17, 20])

mask = (my_list % 2 == 0) & ((my_list % 3 == 0) | (my_list > 10))
result = (my_list[mask] ^ 7) + 2

result

array([ 3, 13, 11, 21])