# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [1]:
! pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip


In [2]:
import numpy as np
import sys

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [3]:
python_array = [0] * 1000
sys.getsizeof(python_array)

8056

In [4]:
numpy_array = np.zeros(1000)
sys.getsizeof(numpy_array)

8112

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [5]:
numpy_array = np.array([1.0, .2, 3.3, 4.4, 5.5])
numpy_array[[0, 2, -1]]

array([1. , 3.3, 5.5])

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [6]:
from itertools import combinations


array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
# write your code here
len_array = len(array)

for i in range(1, len_array):
    for comb in combinations(range(len_array), i):
        if array[list(comb)].sum() == 27:
            print(comb)
            break


(0, 1, 4, 7)


In [7]:
array[[0, 1, 4, 7]].sum()

27.0

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [8]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [9]:
A.mean(axis=0)

array([2. , 8.4])

In [10]:
A.mean(axis=1)

array([3.5, 5. , 7. , 6.5, 4. ])

### Task 5.2 Get the standard deviation by `y` axis

In [11]:
A.std(axis=1)

array([2.5, 3. , 4. , 3.5, 3. ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [12]:
A.sum(axis=1)

array([ 7, 10, 14, 13,  8])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [13]:
A[:2]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [14]:
A[[0, 2, 4]]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [29]:
%time
[i for i in range(1000000)][:10]

CPU times: user 2 µs, sys: 4 µs, total: 6 µs
Wall time: 9.06 µs


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [30]:
%time
np.arange(1000000)[:10]

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.01 µs


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Task 6.2

In [17]:
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%time 
result = unknown_signature(vector1, vector2)
result

CPU times: user 1e+03 ns, sys: 0 ns, total: 1e+03 ns
Wall time: 3.1 µs


32

In [18]:
%time

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
vector1 @ vector2

CPU times: user 1 µs, sys: 0 ns, total: 1 µs
Wall time: 3.81 µs


32

### Task 6.3

In [19]:
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

%time
result = unknown_signature(matrix1, matrix2)
result

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 2.15 µs


[[5, 12], [21, 32]]

In [20]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
%time
matrix1 * matrix2

CPU times: user 2 µs, sys: 1e+03 ns, total: 3 µs
Wall time: 6.91 µs


array([[ 5, 12],
       [21, 32]])

### Task 6.4

In [21]:
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]

%time
result = unknown_signature(lst)
result

CPU times: user 1e+03 ns, sys: 0 ns, total: 1e+03 ns
Wall time: 2.15 µs


3.0

In [22]:
lst = np.array([1, 2, 3, 4, 5])
%time
lst.mean()

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 2.15 µs


3.0

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [23]:
%time
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

CPU times: user 0 ns, sys: 1e+03 ns, total: 1e+03 ns
Wall time: 2.15 µs


[0, 2, 0, 4, 0]

In [24]:
%time
lst = np.array(lst)
lst[mask] = new_value
lst

CPU times: user 1e+03 ns, sys: 1 µs, total: 2 µs
Wall time: 2.86 µs


array([0, 2, 0, 4, 0])

### Task 7.2

In [25]:
%time
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

CPU times: user 1 µs, sys: 0 ns, total: 1 µs
Wall time: 2.15 µs


([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [26]:
%time
list1 = np.array(list1)
list2 = np.array(list2)
result_bitwise_complement = ~list1
result_bitwise_and = list1 & list2
result_bitwise_or = list1 | list2
result_bitwise_complement, result_bitwise_and, result_bitwise_or

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 6.91 µs


(array([ -6,  -3,  -8,  -5, -10]),
 array([1, 2, 1, 0, 8]),
 array([ 7,  6,  7, 12, 11]))

### Task 7.3 Optional

In [27]:
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [28]:
my_list = np.array(my_list)
result_numpy_style = (my_list[(my_list % 2 == 0) & ((my_list % 3 == 0) | (my_list > 10))] ^ 7) + 2
result_numpy_style

array([ 3, 13, 11, 21])