# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [3]:
import datetime

import numpy as np
import sys

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [4]:
list = [0] * 1000
sys.getsizeof(list)

8056

In [5]:
np_list = np.array(list, dtype="int8")
sys.getsizeof(np_list)

1112

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [6]:
float_list = np.array([
    1.0, 2.4, 3.2, 4.5, 5.1, 6.6, 7.3, 8.1, 9.5
], dtype=float)
float_list[[0, 2, -1]]

array([1. , 3.2, 9.5])

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [7]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
int(np.sum(array[[0, 1, -2]]))

27

In [8]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [9]:
np.mean(A, axis=1)

array([3.5, 5. , 7. , 6.5, 4. ])

### Task 5.2 Get the standard deviation by `y` axis

In [10]:
np.mean(A, axis=0)

array([2. , 8.4])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [11]:
np.sum(A, axis=0)

array([10, 42])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [12]:
A[[0, 1]]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [13]:
A[[0, 2, -1]]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [14]:
%timeit [i for i in range(1000000)]

37.4 ms ± 473 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [15]:
%timeit np.arange(1000000)

940 µs ± 4.61 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### Task 6.2

In [16]:
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%timeit unknown_signature(vector1, vector2)

357 ns ± 5.22 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [17]:
np_vector1 = np.array(vector1)
np_vector2 = np.array(vector2)
%timeit np_vector1 @ np_vector2

793 ns ± 1.99 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### Task 6.3

In [18]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]
%timeit unknown_signature(matrix1, matrix2)

890 ns ± 1.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [19]:
np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)
%timeit np_matrix1 * np_matrix2

339 ns ± 1.55 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### Task 6.4

In [20]:
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]
%timeit unknown_signature(lst)

230 ns ± 1.14 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [21]:
np_lst = np.array(lst)
%timeit np_lst.mean()

3.14 µs ± 38.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [22]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[0, 2, 0, 4, 0]

In [23]:
np_lst = np.array([1, 2, 3, 4, 5])
mask = [True, False, True, False, True]
np_lst[mask] = 0
np_lst

array([0, 2, 0, 4, 0])

### Task 7.2

In [24]:
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [25]:
np_lst1 = np.array([5, 2, 7, 4, 9])
np_lst2 = np.array([3, 6, 1, 8, 10])
answer_1 = ~np_lst1
answer_2 = np.bitwise_and(np_lst1, np_lst2)
answer_3 = np.bitwise_or(np_lst1, np_lst2)
answer_1, answer_2, answer_3

(array([ -6,  -3,  -8,  -5, -10]),
 array([1, 2, 1, 0, 8]),
 array([ 7,  6,  7, 12, 11]))